### ISSUE TITLE
Add game validation with NFT Contract

### ISSUE THREAD

**Issue by web3technologies** [realm-of-ra/mancala#100]
When a player creates or joins a game we need to validate that they are an owner of a GamePass NFT. Inside the actions when the functions are called make a call to the nft contract and perform this validation. If no NFT is owned revert the transaction.

**Comment by stevencartavia** [comment]
Hi, can I take this?

**Comment by the-first-elder** [comment]
I can do this.

**Comment by Josh-121** [comment]
I have a good understanding of implementing this and have worked on something similar, this will be my first contribution here if assigned but I'm confident to deliver this. Time frame is within 2days

**Comment by okhaimie-dev** [comment]
@stevencartavia I will assign the task to you. Let us know if you need more clarity, or anything else.
