### ISSUE TITLE
improve ux across application

### ISSUE THREAD

**Issue by xpanvictor** [realm-of-ra/mancala#101]
The goal here is to reduce loading time and where unavoidable, ensure a loading state to improve the overall user experience across the app. Loading the site is a bit slow and can reduce the quality users get from the flow. 

With improving this ux, notice some of these issues
1. Wallet connect modal doesn't close automatically after connection
2. White screens on clicking some of the buttons and links on the game play
3. Some buttons don't respond since they have no listeners

**Comment by xpanvictor** [comment]
1. Wallet connect modal doesn't close automatically after connection
2. White screen

**Comment by okhaimie-dev** [comment]
@xpanvictor will this be a blocker to other developers? and are you will to assist in-case a conflict occurs?

**Comment by xpanvictor** [comment]
It won't, and yh, I'll be up for conflict resolutions.

**Comment by xpanvictor** [comment]
@okhaimie-dev I'll also be making PRs to develop as soon as possible.

**Comment by okhaimie-dev** [comment]
@xpanvictor take a look at this
https://github.com/realm-of-ra/mancala/issues/96

and work with the developer assigned to this issue, to make sure there is no conflict here.

**Comment by xpanvictor** [comment]
Noted

**Comment by xpanvictor** [comment]
https://github.com/realm-of-ra/mancala/pull/133
