### ISSUE TITLE
implementation of logic for a user duels

### ISSUE THREAD

**Issue by supreme2580** [realm-of-ra/mancala#105]
This is the user duels screen

![image](https://github.com/realm-of-ra/mancala/assets/100731397/53369664-0439-454d-b96d-2211437db2d7)

Data needs to be fetched from our torii endpoint (using apollo which we've already configured) and be used  to populate the fields.

The image and name comes from the starknetid data of the wallet address, if a starknet name does not exist you can use the truncated version of the wallet address, we already have a function to truncate a wallet address it is called ```truncateString```,  while it is loading you can use a skeleton instead of an empty/broken field, you can get the date of the duel by also querying the same torii endpoint transactions field.

Our torii endpoint: `https://api.cartridge.gg/x/mancala/torii/graphql`

**Comment by EjembiEmmanuel** [comment]
D

**Comment by Gift-Naomi** [comment]
H

**Comment by EmmanuelAR** [comment]
Hey @supreme2580 can I work on this?

**Comment by supreme2580** [comment]
Hi guys you can reach out to us on telegram for more information about any issue you might be facing, the ideal timeline is 2 days for an update of how the issue is going.

https://t.me/+0UKU3P3Eh_s2NTRh

**Comment by kelvido** [comment]
Hi guys, I would love to work on this too
