### ISSUE TITLE
Add functionality to the other parts of the game

### ISSUE THREAD

**Issue by supreme2580** [realm-of-ra/mancala#108]
A few things in this game still needing functionality are

- Players and their stats, implementation of levels and scores based on wins and losses from the graph (Draws are not possible...) 
- Join/Create game button in duels should be changed to look like that of the design
- I think there is already a PR for the connect button
- Implementation of data for leaderboard logic from graph (formula for score and levels based on wins/losses should also be created)

For the levels formula, we are doing minimum of 1 then every four wins is 1 level up, then scores are wins * 50.

To get the total number of wins we fetch all the instances where a user address is the winner of the game and the length of the array is the total number wins

For implementing restart and end game functionality there is already an issue created to add this to the contract, when that is done it will be possible to call those functions on the frontend

**Comment by Oshioke-Salaki** [comment]
I’ll do it

**Comment by josephchimebuka** [comment]
Can I hop on this??

**Comment by Josh-121** [comment]
new contributing on here but have a software engineering background, with a little bit of game dev, also quite familiar with cairo.
I'm quite confident in handling these.

https://app.onlydust.com/u/Josh-121

**Comment by ktarun1419** [comment]
Hi @okhaimie-dev @supreme2580   i want to work on this one
