### ISSUE TITLE
feat: animate game stone movement

### ISSUE THREAD

**Issue by okhaimie-dev** [realm-of-ra/mancala#116]
## context
https://youtu.be/h0xHXv3y-p4

issue discussed on telegram gc: https://t.me/+0UKU3P3Eh_s2NTRh

**Comment by Dprof-in-tech** [comment]
Hello @okhaimie-dev 
I would love to work on this

**Comment by Joy-Adah** [comment]
Hi @okhaimie-dev I'd love to take this up if it hasn't been resolved.

**Comment by od-hunter** [comment]
can i work on this asap if it hasn't been resolved @okhaimie-dev

**Comment by Jemiiah** [comment]
@okhaimie-dev can I work on this  ?
