### ISSUE TITLE
Frontend contract call fix and UI upgrade

### ISSUE THREAD

**Issue by supreme2580** [realm-of-ra/mancala#128]
Fix the following things

 - Remove white screen after the icon on the header is clicked
 - Remove white screen after the go to game button is clicked on the live duels screen
 - Fix the create public game contract call
 - Fix the public game contract call
 - Fix the join game contract call
 - Fix the move contract call
 - Turn seeds into a component
 - Update the package.json to a stable version of dojoengine and latticexyz

**Comment by Oshioke-Salaki** [comment]
Hello can I handle this? I am a well skilled front end developer
