### ISSUE TITLE
Change <a> tag to <Link /> in Lobby to leaderboard

### ISSUE THREAD

**Issue by supreme2580** [realm-of-ra/mancala#130]
Change `<a />` tag to `<Link />` in Lobby to leaderboard

**Comment by EjembiEmmanuel** [comment]
@supreme2580 I'd love to work on this

**Comment by nemealfaro** [comment]
Hi, I'm Nemesis Alfaro from Costa Rica, i'm a system engineer and web developer on CNFL company.
I'm hard-working, constant and curious person
This would be my first contribution on the platform, in order to gain more knowledge and improve in the area.
