### ISSUE TITLE
Whitescreen on page load

### ISSUE THREAD

**Issue by xpanvictor** [realm-of-ra/mancala#139]

**Comment by od-hunter** [comment]
can i have this @xpanvictor

**Comment by xpanvictor** [comment]
I'm done with this already chief. It was an early bug we noticed and needed a quick fix.

**Comment by od-hunter** [comment]
Ok sir.

**Comment by okhaimie-dev** [comment]
you'd still get whitescreen @xpanvictor. this time it is an issue with the mancala torii server. I am trying to dig deeper into it

**Comment by xpanvictor** [comment]
@okhaimie-dev I added a fallback to an error boundary. So it shows an error page with the error details
