### ISSUE TITLE
Add custom move events to contract

### ISSUE THREAD

**Issue by okhaimie-dev** [realm-of-ra/mancala#194]
We need to add custom Dojo events to track important game actions in the Mancala game. This will improve the user experience by allowing the frontend to react to game state changes and provide better visual feedback.

### 1. Capture Event
**Purpose:** Track when a player captures seeds from opponent's pit
```cairo
#[derive(Copy, Drop, Serde)]
#[dojo::event(historical: true)]
struct Capture {
    #[key]
    game_id: u128,
    player: ContractAddress,
    pit_number: u8,
    seed_count: u8,
}
```

### 2. End Turn Event
**Purpose:** Signal when a player's turn ends and next player begins
```cairo
#[derive(Copy, Drop, Serde)]
#[dojo::event(historical: true)]
struct EndTurn {
    #[key]
    game_id: u128,
    current_player: ContractAddress,
    next_player: ContractAddress,
}
```

### 3. Extra Turn Event
**Purpose:** Indicate when a player earns an extra turn
```cairo
#[derive(Copy, Drop, Serde)]
#[dojo::event(historical: true)]
struct PlayerExtraTurn {
    #[key]
    game_id: u128,
    player: ContractAddress,
}
```

## Implementation Tasks

1. **Event Definitions**
   - [ ] Add event structures in `events/index.cairo`
   - [ ] Create trait implementations in `events/move.cairo`

2. **Store Updates**
   - [ ] Add emission methods in `store.cairo`

3. **Game Logic Integration**
   - [ ] Modify `move` function in `components/playable` to emit Capture, EndTurn & ExtraTurn event

**Comment by dahtee** [comment]
Hi @okhaimie-dev can I quickly implement this?
ETA: 24hrs
