### ISSUE TITLE
Create UI/UX design for Profile Page

### ISSUE THREAD

**Issue by supreme2580** [realm-of-ra/mancala#201]
Create the UI/UX design for the mancala game profile section, a few things we expect to be there are
- The name of the user (or their truncated wallet address if they have not added a name)
- The edit profile page/modal
- User stats such as wins, losses and draws
- A section to see all their games
This page should follow the already existing UI flow of the lobby design page.

**Comment by od-hunter** [comment]
Hi @supreme2580 , can I be assigned this please?

**Comment by Reallanky** [comment]
Hi @supreme2580 can I be assigned this issue please, delivery will be timely.

**Comment by IamEnergyI** [comment]
Hi @supreme2580 
Can i be assigned 

Layout and Information Hierarchy:

Group player stats (level, total played, wins/losses) together for better readability
Prioritize the player's name and profile picture as the focal point
Use whitespace effectively to create a clean, uncluttered appearance

Visual Design:

Align the color scheme with the game's overall branding and aesthetics
Incorporate subtle visual treatments, such as soft gradients or iconography, to enhance the interface
Ensure typography, spacing, and alignment create a cohesive, polished look

Interactivity:

Make the "Change Photo" button more visually prominent, perhaps with a contrasting color or hover effect
Consider adding subtle animations or transitions to create a more responsive feel
Explore the possibility of adding additional customization options, like the ability to change the display name

Responsive Design:

Ensure the layout and elements adapt seamlessly to different screen sizes, from desktop to mobile
Optimize the interface for both touch-based and mouse/keyboard interactions

Consistency:

Align the profile interface's visual style and interactions with the rest of the game's user interface
Ensure the profile section integrates seamlessly with the larger game experience, creating a cohesive user journey
