### ISSUE TITLE
Add Contract logic to set the MancalaGame state winner after the game is completed.

### ISSUE THREAD

**Issue by web3technologies** [realm-of-ra/mancala#21]
The MancalaGame model is defined like this:
`#[derive(Model, Copy, Drop, Serde, Debug)]
struct MancalaGame {
    #[key]
    game_id: u128,
    player_one: ContractAddress,
    player_two: ContractAddress,
    current_player: ContractAddress,
    winner: ContractAddress, // todo implement logic to set this state
    is_finished: bool,
}`

When a game is finished, marked by one of the players having all of their pits emptied, add logic to set the state of the winner = to the winner of the game

Add Unit tests to ensure this is working correctly.

**Comment by mul1sh** [comment]
@web3technologies @okhaimie-dev Kindly let me have a crack at this 🙂

**Comment by web3technologies** [comment]
> @web3technologies @okhaimie-dev Kindly let me have a crack at this 🙂

I updated the description but be sure to add some unit testing!

**Comment by mul1sh** [comment]
Sorry for the delay with this, I was understanding dojo and it took a bit longer than I anticipated. Will push a PR with the implementation in a few 🙂

**Comment by web3technologies** [comment]
@mul1sh How's progress on this? Do you need any assistance?

**Comment by mul1sh** [comment]
> @mul1sh How's progress on this? Do you need any assistance?

Naah i'm good 🙂 Had to revisit the dojo docs 1 more time, pushing a PR in a few hours

**Comment by mul1sh** [comment]
@web3technologies I think this issue was actually fixed in this [commit](https://github.com/realm-of-ra/mancala/commit/9e85a1a5269f712f3cc4b167610f05e4b993aba1) if i'm not wrong 🤔

**Comment by web3technologies** [comment]
Yes that is correct

**Comment by web3technologies** [comment]
Closed per this commit: https://github.com/realm-of-ra/mancala/commit/9e85a1a5269f712f3cc4b167610f05e4b993aba1
