### ISSUE TITLE
Add Status enum to MancalaGame

### ISSUE THREAD

**Issue by web3technologies** [realm-of-ra/mancala#23]
An enum with status PENDING, IN_PROGRESS, FINISHED, FORFEITED should be added to the MancalaGame storage with a field named "status". Then these status should be updated upon different functions in the game.

When a game is created the game should be status PENDING
When a player_two joins the game the status should be IN_PROGRESS
If the game is forfeited the game status should be updated to FORFEITED
When the game is over the status should be set to FINISHED

Dojo documentation on implementing Enums into Models: https://book.dojoengine.org/framework/models/enum

**Comment by TEMHITHORPHE** [comment]
Can I take this ?, is it assigned yet ?

**Comment by okhaimie-dev** [comment]
@TEMHITHORPHE I just assigned this to you

**Comment by TEMHITHORPHE** [comment]
🚀 Acknowledged sensei 🥲

**Comment by web3technologies** [comment]
@TEMHITHORPHE do you have any status updates on this task? Are there any blockers or do you need some assistance?

**Comment by TEMHITHORPHE** [comment]
Hey mahn, apologies for going AWOL on this, had serious health challenges, made me forgot I had a commitment somewhere.
