### ISSUE TITLE
Create test for the Capture logic

### ISSUE THREAD

**Issue by web3technologies** [realm-of-ra/mancala#24]
In the contract code we do not yet have logic to test that captures are working successfully. The test exists but the capture logic is not being tested. We need to write a test for this and ensure that all of it is functioning properly.

The test can be found here. https://github.com/realm-of-ra/mancala/blob/develop/contracts/src/tests/test_world.cairo#L115
The implementation of the capture logic can be found here: https://github.com/realm-of-ra/mancala/blob/develop/contracts/src/models/mancala_game.cairo#L167

**Comment by Ugo-X** [comment]
please can i be assigne to this?

**Comment by mubarak23** [comment]
@web3technologies kindly assign this issue to me.

**Comment by web3technologies** [comment]
@mubarak23 do you have any updates or need any assistance with this issue?

**Comment by xpanvictor** [comment]
The capture implementation is now at https://github.com/realm-of-ra/mancala/blob/7a80ad80c38762acbfd1d01ad886a68bf68b1dbc/contracts/src/models/mancala_game.cairo#L188 and test at https://github.com/realm-of-ra/mancala/blob/7a80ad80c38762acbfd1d01ad886a68bf68b1dbc/contracts/src/tests/test_world.cairo#L164

**Comment by web3technologies** [comment]
@xpanvictor yes these functions already exist and we need to test that the capture logic is properly implemented. Are you wanting to take this issue?

**Comment by xpanvictor** [comment]
Yes, assign me to this, I'll work on it @web3technologies

**Comment by manlikeHB** [comment]
Hi @web3technologies, I have experience implementing a starknet component and writing test for it from the previous ODHack, I would be a perfect fit for this issue.

**Comment by No-bodyq** [comment]
Hello @web3technologies, can I get assigned this issue. Here is my profile https://app.onlydust.com/u/No-bodyq
I have some experience writing tests as you may see on my profile

**Comment by the-first-elder** [comment]
I can do this

**Comment by Josh-121** [comment]
I've looked into this and I'm confident in delivering this if assigned. 2-3 days

**Comment by No-bodyq** [comment]
![image](https://github.com/realm-of-ra/mancala/assets/141028690/6bcc8b23-fd18-481e-bb40-741246e017ab)
Hello, Can i have some assistance with this... I'm working from a codespace. I've installed dojo and scarb but i keep getting this error code whenever i try to run `scarb test`  or scarb cairo-test. Am i missing something?

**Comment by okhaimie-dev** [comment]
@No-bodyq you cannot use `Scarb` as a package manager for dojoengine.

Install dojo https://book.dojoengine.org/getting-started#install-using-dojoup and then use `sozo test`

Maybe go through this tutorial to help you get familiar with dojo
https://book.dojoengine.org/tutorial/dojo-starter

Feel free to join project telegram if you need further assistance:
https://t.me/+0UKU3P3Eh_s2NTRh
