### ISSUE TITLE
Integrate Push Protocol for Chat

### ISSUE THREAD

**Issue by supreme2580** [realm-of-ra/mancala#27]
## Description

We need to enable player interaction within our React application for an on-chain game. Players should be able to communicate with each other while playing the game. We have a UI design that showcases how this interaction will work.
To implement this feature, we'll be using the Push Protocol, which supports chain-agnostic wallet addresses for user identification. The Push Protocol documentation provides guidance on how to integrate it into our application.
### Tasks:

1. Review the UI design.
2. Set up the necessary dependencies and environment for integrating the Push Protocol into our React application.
3. Implement the Push Protocol's chat functionality as per the documentation:
- 
  - Initialize the Push SDK with the appropriate configuration.
  - Implement the necessary components and hooks to handle user authentication and wallet address resolution.
  - Create the chat UI components based on the provided design.
  - Integrate the Push Protocol's chat APIs to enable real-time messaging between players.
  - Handle error cases and edge scenarios gracefully.

References:

Push Protocol Documentation: https://push.org/docs/chat/supported-wallet-standards/#chain-agnostic-wallet-address
UI Design:
![CleanShot 2024-05-22 at 01 03 55](https://github.com/realm-of-ra/mancala/assets/57156589/4c523758-a152-4faf-b6d7-5958e99266a4)

**Comment by Jemiiah** [comment]
can I work on this

**Comment by Jemiiah** [comment]
🚀
