### ISSUE TITLE
Add volume control for background music

### ISSUE THREAD

**Issue by supreme2580** [realm-of-ra/mancala#28]
Add volume control for background music on the mute and unmute buttons across each screen

![CleanShot 2024-06-11 at 13 44 25@2x](https://github.com/realm-of-ra/mancala/assets/57156589/e5454473-5ab7-4321-816c-9fb2f9731231)

![CleanShot 2024-06-11 at 13 44 50@2x](https://github.com/realm-of-ra/mancala/assets/57156589/b7cf7118-a09b-45b5-8cf4-dcef79dfa7c3)

**Comment by jezastudio** [comment]
I would like to be assigned this

**Comment by Dprof-in-tech** [comment]
Hello chief I would love to work on this

**Comment by supreme2580** [comment]
sure

**Comment by jezastudio** [comment]
I was unassigned

**Comment by Dprof-in-tech** [comment]
Hello @supreme2580 , there is no clear contribution guide on how I can clone this project and start working on it
Also tried installing dependencies for the client but keep getting an error

**Comment by supreme2580** [comment]
Thank you for the suggestion, will update the readme, by the way what's the error you're getting?

**Comment by Dprof-in-tech** [comment]
![image](https://github.com/realm-of-ra/mancala/assets/116242877/e433aae1-238e-40f3-abe5-e4de0354c1c6)
first got this then i installed it with legacy peer deps and then I got the one below

![image](https://github.com/realm-of-ra/mancala/assets/116242877/048ecbc2-0a0c-4354-be90-30ed3bddd833)
