### ISSUE TITLE
Add a screen to block users from viewing from an unsupported device size

### ISSUE THREAD

**Issue by supreme2580** [realm-of-ra/mancala#29]
Add an overlay that blocks users viewing from a device which have a screen width of less than 1280px, for these users it should tell them "this game is not optimized for this device".

**Comment by Oshioke-Salaki** [comment]
please can i have this?

**Comment by supreme2580** [comment]
Sure

**Comment by Dprof-in-tech** [comment]
Hi chief I would love to work on this

**Comment by okhaimie-dev** [comment]
@all-contributors please add @Oshioke-Salaki for code.
