### ISSUE TITLE
Integrate smart contract functions

### ISSUE THREAD

**Issue by supreme2580** [realm-of-ra/mancala#30]
Integrate smart contract functions on testnet to make the game playable on the blockchain.

**Comment by Calebux** [comment]
i want to do this

**Comment by kateberryd** [comment]
I would love to work on this

**Comment by Ugo-X** [comment]
please can i be assigned to this?

**Comment by okhaimie-dev** [comment]
this issue is not yet ready. I'll add more details in a bit

**Comment by Ugo-X** [comment]
> this issue is not yet ready. I'll add more details in a bit

alright chief, i am active

**Comment by kateberryd** [comment]
Alright @okhaimie-dev
