### ISSUE TITLE
Create game restart functionality

### ISSUE THREAD

**Issue by web3technologies** [realm-of-ra/mancala#42]
We need a player to be able to restart a game. Add a new function on the MancalaGame model that will restart the game.

**Comment by Iwueseiter** [comment]
Hi

**Comment by web3technologies** [comment]
Hi @Iwueseiter happy to see your interest. What is your timeline for completion? We are in need of this logic completion ASAP

**Comment by Iwueseiter** [comment]
3 working days maximum.

**Comment by web3technologies** [comment]
@Iwueseiter the task has been assigned to you.

**Comment by web3technologies** [comment]
@Iwueseiter Whats your progress on this issue?

**Comment by Iwueseiter** [comment]
@web3technologies I've started working on this and will create  PR as soon as possible.

**Comment by the-first-elder** [comment]
I can do this

**Comment by Josh-121** [comment]
Having going through the code base I think I can be able to deliver on this within 3days. I have some logic in place
