### ISSUE TITLE
Create Forfeit Game Logic

### ISSUE THREAD

**Issue by web3technologies** [realm-of-ra/mancala#44]
We need a new function that will allow a user to forfeit the game.

**Comment by princeibs** [comment]
Can I hop on this?

**Comment by princeibs** [comment]
Can I hop on this?

**Comment by web3technologies** [comment]
I would assign this to you however this is a blocker currently: https://github.com/realm-of-ra/mancala/issues/23

**Comment by web3technologies** [comment]
@princeibs if you would like to take https://github.com/realm-of-ra/mancala/issues/23 and implement this logic you can

**Comment by princeibs** [comment]
Yeah sure. I would like to first tackle issue 23 @web3technologies

**Comment by web3technologies** [comment]
@princeibs I have completed issue 23 you can now move forward with this issue.

**Comment by Josh-121** [comment]
Pls can I work on this?

**Comment by Josh-121** [comment]
I have a good understanding on how to go about this from reviewing the code. I have had to implement things like this in the past. Should deliver within 2days

**Comment by Dprof-in-tech** [comment]
Hello @web3technologies 
Its Isaac here and i would love to work on this issue.

I understand that I have to implement function which should take the forfeiting users id, end the game and add the game id as a loss to the forfeiting player id in the updated player model

I have been successfully contributing to starknet projects and would love to work on this issue.

here is my onlydust profile
https://app.onlydust.com/u/Dprof-in-tech

**Comment by Josh-121** [comment]
> I have a good understanding on how to go about this from reviewing the code. I have had to implement things like this in the past. Should deliver within 2days

I'm looking to make my first contribution on here but regardless, I have extensive experience in software & game dev so I'm quite confident and happy to work on this
