### ISSUE TITLE
Design Landing Page

### ISSUE THREAD

**Issue by Israelrex9** [realm-of-ra/mancala#51]
Design landing page for realm of ra, linked to Mancala on figma

**Comment by okhaimie-dev** [comment]
@all-contributors 
please add @Israelrex9 for design. 
please add @web3technologies for code. 
please add @supreme2580 for code.
please add @xpanvictor for code.
please add @Ajiboyeniola for code.
please add @Oshioke-Salaki for code.
please add @okhaimie-dev for docs

**Comment by okhaimie-dev** [comment]
@all-contributors please add @Israelrex9 for design

**Comment by okhaimie-dev** [comment]
@all-contributors please add @Israelrex9 for design.
