### ISSUE TITLE
Integrate Join Game functionality into the frontend

### ISSUE THREAD

**Issue by web3technologies** [realm-of-ra/mancala#59]
When navigating to the Live Duels tab there is a Join Game button. This needs to connect with the smart contract to call the join_game function in order for a player to join the game

**Comment by kateberryd** [comment]
Can I work on this

**Comment by estherbreath** [comment]
@web3technologies I am a smart contract developer, with experience in Frontend development as well.
I would like to be assigned this issue

What I will do is to integrate the "Join Game" functionality with the smart contract's join_game function in the Mancala game.

My knowledge in smart contract will help in reviewing code to locate the join_game function within the smart contract. Understanding its purpose, inputs, and outputs is crucial for successful integration.

Connection using a Frontend Framework and interacting with the contract will be the next thing.

**Comment by web3technologies** [comment]
Hi @kateberryd @estherbreath I will assign both of you this issue. You can both work on it and submit your PR's. We will review both of them prior to merge.

**Comment by estherbreath** [comment]
@web3technologies Please who do I contact on telegram?

**Comment by web3technologies** [comment]
You can contact me at @zachcook

**Comment by okhaimie-dev** [comment]
I am going to close this issue now @estherbreath @kateberryd 

we are trying to move fast internally so we can have better issues that aren't blockers for y'all at the OnlyDust hack coming up in 2 weeks.
