### ISSUE TITLE
Implement the move logic into the frontend

### ISSUE THREAD

**Issue by web3technologies** [realm-of-ra/mancala#60]
When clicking on a pit the move function should be called on the smart contract.

**Comment by EjembiEmmanuel** [comment]
Hello @web3technologies I'd love to work on this

**Comment by Ugo-X** [comment]
Good morning, my name is Ugo and I am a fullstack Dev. I love what Mancala is building and I would love to contribute to this project, If need be describe the approach I would use to get this done, I can comment below. Please can I be assigned this task?

**Comment by okhaimie-dev** [comment]
@EjembiEmmanuel @Ugo-X 

we are trying to build this internally to prepare better issues for y'all during the ODHack.

**Comment by okhaimie-dev** [comment]
@all-contributors please add @supreme2580 for code.
