### ISSUE TITLE
Create General documentation

### ISSUE THREAD

**Issue by web3technologies** [realm-of-ra/mancala#61]

**Comment by Joy-Adah** [comment]
Hi @okhaimie-dev @web3technologies can I work on this?

**Comment by xpanvictor** [comment]
What structure do we want to use for documentation? 
Will a readme do or do we generate a standard doc with cairo-docgen? 
Markdown should be good with the frontend

**Comment by okhaimie-dev** [comment]
@xpanvictor this will be a general doc to help people get more acquainted to the codebase and game during the OnlyDust hack.

We have a [vocs.dev book](https://github.com/realm-of-ra/mancala/tree/develop/book) for this documentation, and yes it uses `mdx`

**Comment by HumbertoTM10** [comment]
Hi! Is this still available to work on?

**Comment by estheroche** [comment]
can i take this up?

**Comment by od-hunter** [comment]
Can I take this up please? @okhaimie-dev 
I’m very good at documentations🙏🏾

**Comment by Gift-Naomi** [comment]
@web3technologies I will like to be assigned in this issue if no one is currently working on it, I am a smart contract developer and also a technical writer, here is my onlydust profile https://app.onlydust.com/u/Gift-Naomi.
Here are some of the documentations I have written https://hackmd.io/@xZ4BOZ5TTTy1I0ZQHXFOkg/HJigwk5NC, https://github.com/paltalabs/create-soroban-dapp/commit/61919f9d949cd39d324501f7283c8f8d7344cb64, https://github.com/horuslabsio/Starknet-Scaffold/blob/main/docs/src/chapter_7.md.

**Comment by VictoriaAde** [comment]
**I would like to take up this issue if it can accept more contributors.**

**Comment by okhaimie-dev** [comment]
@od-hunter @VictoriaAde 

Can y'all show more some of your previous work ass technical writers?

**Comment by od-hunter** [comment]
Hello @okhaimie-dev , here are some of my documentations that were merged:
https://github.com/keep-starknet-strange/joyboy/pull/143#event-13034455918

https://github.com/horuslabsio/Starknet-Scaffold/pull/94#event-13007360671

Here are the links to some of my writings off GitHub:
 https://t.co/ZgK0ccPZpw
 
https://t.co/GnBqVQPECz

Please check them out🙏🏾

**Comment by VictoriaAde** [comment]
> @od-hunter @VictoriaAde
> 
> Can y'all show more some of your previous work as technical writers?

Here are mine

https://medium.com/web3-writers-guild/multicall-smart-contract-for-gas-optimization-961d7adc6c2a

https://medium.com/web3-writers-guild/an-erc721-non-fungible-token-nft-smart-contract-cf53126accf7

https://medium.com/web3-writers-guild/nodes-and-clients-json-rpc-96d0c89c9345

**Comment by Gift-Naomi** [comment]
> Hi @okhaimie-dev pease I would like to be assigned in this issue, I am a smart contract developer and also a technical writer, here is my onlydust profile https://app.onlydust.com/u/Gift-Naomi. Here are some of the merged documentations I have written https://hackmd.io/@xZ4BOZ5TTTy1I0ZQHXFOkg/HJigwk5NC, [paltalabs/create-soroban-dapp@61919f9](https://github.com/paltalabs/create-soroban-dapp/commit/61919f9d949cd39d324501f7283c8f8d7344cb64), https://github.com/horuslabsio/Starknet-Scaffold/blob/main/docs/src/chapter_7.md.

Here are mine.
