### ISSUE TITLE
Refr: Message area code can be refactored 

### ISSUE THREAD

**Issue by xpanvictor** [realm-of-ra/mancala#73]
The message area is the section that shows users whose turn to play or if one clicked the right pit. Review this section to optimize the logic or style.
Pull from develop branch and submit a PR

**Comment by xpanvictor** [comment]
https://github.com/realm-of-ra/mancala/blob/976e237378cd09a837ce80cac3e2cd26f56d939b/client/src/pages/games/Gameplay.tsx#L499

The source is here

**Comment by fishonamos** [comment]
I can work on this.

**Comment by okhaimie-dev** [comment]
@all-contributors please add @xpanvictor for code.
