### ISSUE TITLE
Mancala Board

### ISSUE THREAD

**Issue by Israelrex9** [realm-of-ra/mancala#97]
Description; Exactly replicate the figma design of the Manacala Game board

- Use gradients to show the depth of each pot on the board.
- For the main side pots (2), adjust the gradients to accurately represent their depth.
- Position the "number of seeds within each pot" according to the layout shown in Figma.
- The seed color should be #D9D9D9.

Figma for reference; https://www.figma.com/design/6fQvKQWmxnt0XLUSjBjecj/MANCALA-Game-UI?node-id=1141-16535&m=dev

How it looks right now
![Screenshot 2024-06-19 at 1 27 30 AM](https://github.com/realm-of-ra/mancala/assets/46507005/3ced5e34-8b90-453c-8b34-7b2b2a95ef2a)

How it should look as its on figma
![Screenshot 2024-06-19 at 1 28 07 AM](https://github.com/realm-of-ra/mancala/assets/46507005/c1a1dbb3-d57c-4974-8b60-13efe1356f6e)

**Comment by od-hunter** [comment]
Can I be assigned this issue? I have extensive knowledge of Figma and I’m a developer, I’ll like to be given the opportunity to apply my skills please?

**Comment by Osatuyi** [comment]
@Israelrex9 can I be assigned this issue, please. I'm a product designer and can delever a clean design.

**Comment by Israelrex9** [comment]
✨ When applying for a task, please include a brief description of your experience and an estimated time frame for completion.

**Comment by od-hunter** [comment]
As a UI/UX Designer, I have extensive experience in creating user-centered designs that enhance user experiences and meet business objectives. My expertise includes:

User Research, wireframing and prototyping, Visual Design, Interaction Design and collaboration.

As a Full-Stack Blockchain Developer, I possess a robust skill set in both front-end and back-end development, My experience includes html, css, react, JavaScript Cairo ,TypeScript, rust and small knowledge on GO.

I’d have my PR ready in less than 24 hours once I’m assigned.

**Comment by Osatuyi** [comment]
@Israelrex9, can I be assigned this issue, please. I'm a product designer with almost 2 years of experience in this field and can deliver a clean design in 3 days.

https://www.figma.com/design/ziGnFqAHvDKbjr3JNoK7NX/Portfolio?node-id=168-345&t=C6TaonHUTQAcYtMO-0

**Comment by Israelrex9** [comment]
> @Israelrex9, can I be assigned this issue, please. I'm a product designer with almost 2 years of experience in this field and can deliver a clean design in 3 days.
> 
> Here are some things I've done. https://www.figma.com/design/ziGnFqAHvDKbjr3JNoK7NX/Portfolio?node-id=168-345&t=C6TaonHUTQAcYtMO-0

Hello, really nice figma, but this is a frontend development task.

**Comment by kateberryd** [comment]
Hi @Israelrex9 I'm an experienced frontend developer and I would love to contribute to this projects.  Below is my onlydust profile and also frontend contributions I've done 
[https://app.onlydust.com/u/kateberryd](https://app.onlydust.com/u/kateberryd)

**Comment by Dprof-in-tech** [comment]
Hello I’m Isaac, a full-stack JavaScript developer with a proven track record of contributing to starknet and od hack projects
here is my OnlyDust profile 
https://app.onlydust.com/u/Dprof-in-tech

To solve this issue I would follow the due instructions using CSS elements to position and achieve the needed design look from the figma file, noting the properties of each widget so I can give a pixel-perfect job.

I would deliver this task within a timeline of 2 days given no blockers and if there are any I would make sure to provide a notice beforehand

May I be assigned to this task so I can start off with my solution?

**Comment by Ayoazeez26** [comment]
Hi @Israelrex9 I am a frontend developer with a knack for pixel perfect implementation and I would love to work on this issue
Here is my onlydust profile: https://app.onlydust.com/u/Ayoazeez26
Here is my github profile: https://github.com/Ayoazeez26
I would take 2 working days to deliver this task unfailingly

**Comment by PoulavBhowmick03** [comment]
I would love to work on this issue. i am a full stack web3 developer. I have been exploring Mancala since last day and have gone through the codebase and I reckon I can solve this issue
Here is my Profile:- https://app.onlydust.com/u/PoulavBhowmick03
Not much, since recently opened the account, but I can get this done

**Comment by okhaimie-dev** [comment]
@kateberryd I just assigned this task to you. Let me know if you need help with anything else

**Comment by kateberryd** [comment]
@okhaimie-dev Thank you. I'll communicate on telegram
